exports.seed = knex => {
  // Deletes ALL existing entries
  return knex('restaurants').insert([
        {id: 1, name: 'Lost Lake Cafe & Lounge', street_address: '1505 10th Ave', city: 'Seattle', state: 'WA', zip: 98122, neighborhood: 'Cap Hill', cost: '$', cuisine: 'Americana', website: 'https://www.lostlakecafe.com/', description: `Delicious, laid back lounge modeled after the locally shot Twin Peaks mystery thriller.`},
        {id: 2, name: 'Bar del Corso', street_address: '3057 Beacon Ave S', city: 'Seattle', state: 'WA', zip: 98144, neighborhood: 'Beacon Hill', cost: '$$', cuisine: 'Pizza', website: 'http://www.bardelcorso.com/', description: `Bar del Corso is a pizzeria, restaurant and bar in the Beacon Hill neighborhood of Seattle, featuring wood-fired pizza, and Italian small dishes. We showcase local, seasonal produce, Italian salumi and cheese, and regional Italian wines. Classic Italian cocktails, local craft beer, cider, and spirits are served from our bar. Our bread and desserts are made in-house, with espresso and after dinner drinks available.`},
        {id: 3, name: 'Altstadt', street_address: '209 1st Avenue South', city: 'Seattle', state: 'WA', zip: 98104, neighborhood: 'Pioneer Square', cost: '$$', cuisine: 'German', website: 'http://www.altstadtseattle.com/', description: `Altstadt is a unique experience in Pioneer Square and Seattle in general. We make the unfamiliar (whether it be beer, liquor, or food) familiar and bring the German hospitality traditions to our own community. With a warm, homey atmosphere and product found nowhere else in the area, we know the experience of coming to Altstadt is one of a kind, whether it be a guest’s first, or fiftieth time.`},
        {id: 4, name: 'Che Sara Sara', street_address: '222 1st Avenue South', city: 'Seattle', state: 'WA', zip: 98104, neighborhood: 'Pioneer Square', cost: '$$', cuisine: 'Italian', website: 'http://seattleslittleitaly.com/che-sara-sara/', description: `Che Sara Sara is a 20-seat restaurant almost exclusively serving the food and wine of the Puglia region of Italy.  This is one of the only mono, regional restaurants (of any type) in all of Seattle.  Enjoy traditional dishes from Puglia, such as O recchiette Con Broccoli De Rape and stop by for l’aperitivo!`},
        {id: 5, name: `Café Pettirosso`, street_address: `1101 E Pike St `, city: 'Seattle', state: 'WA', zip: 98122 , neighborhood: `Capital Hill`, cost: `$$`, cuisine: `Local Fresh`, website: `pettirossoseattle.com`, description: `daily breakfast, lunch, happy hour and dinner menu, we also cater and bake cakes to order.  A full pastry case and espresso bar serving locally roasted Lighthouse Roasters greets you at the front door, followed by our bar, stocked full with spirits, both local and international.`},
{id: 6, name: `Quinn's`, street_address: `1001 E PIike St`, city: 'Seattle', state: 'WA', zip: 98122 , neighborhood: `Capital Hill`, cost: `$$`, cuisine: `Pub`, website: `quinnspubseattle.com`, description: `At Quinn’s Pub we take traditions of the classic public house and raise them to new levels. We are community driven, quality focused, continual experiment in what it means to be a pub. Our food is refined takes on traditional pub fare, our bar carefully curated, and our space open to all.`},
{id: 7, name: `Metier`, street_address: `1017 E Union St`, city: 'Seattle', state: 'WA', zip: 98122, neighborhood: `Capital Hill`, cost: `$$`, cuisine: `Americana`, website: `metierseattle.com`, description: `At Métier we’re committed to creating fresh and flavorful food for people who value quality and health. Our menu features fresh salads, bowls, waffles and smoothies that are rich in energy and full of flavor. Join us for coffee, breakfast, come in for lunch, or meet up with friends for our happy hour small plates.`},
{id: 8, name: `Ramen Man`, street_address: `1616 N 45th St`, city: 'Seattle', state: 'WA', zip: 98103, neighborhood: `Wallingford`, cost: `$`, cuisine: `Japanese`, website: `too cool for the web`, description: `Just off 45th, Ramen Man is all about simplicity, man, so while their menu might seem quite basic, their broth packs a flavorful punch, and the best part? Ramen Man offers unlimited boiled eggs with your bowl of ramen.`},
{id: 9, name: `Red Cow`, street_address: `1423 34th Ave`, city: 'Seattle', state: 'WA', zip: 98122, neighborhood: `East Capital Hill`, cost: `$$$`, cuisine: `Americana`, website: `ethanstowellrestaurants.com`, description: `Lively upscale brasserie offering steak frites & other French classics along with cocktails & wine.`},
{id: 10, name: `Black Duck Cask and Bottle`, street_address: `317 NW Gilman Blvd #31-B`, city: 'Issaquah', state: 'WA', zip: 98027, neighborhood: `Across the Water`, cost: `$$`, cuisine: `Americana`, website: `theblackduckcaskandbottle.com`, description: `One of the only places outside of Seattle. To get this one, you have to face the dangers of cross one of the bridges eastbound. Easily top five burgor and the pizza is incredible. Candidly, the menu is incredible top to bottom including the cocktails and tap list. If in Seattle, this would be a top three restaurant.`},
{id: 11, name: `Dino's Tomato Pie`, street_address: `1524 E Olive Way`, city: 'Seattle', state: 'WA', zip: 98122, neighborhood: `Capital Hill`, cost: `$$`, cuisine: `Pizza`, website: `dinotomatopie.com`, description: `Dino's is a hot place, often literally, with pizza coming in two different crust types. Make sure to get both…and don't forget to visit the website, top 5 all time.`},
{id: 12, name: `Queen Anne Beerhall`, street_address: `203 W Thomas St`, city: 'Seattle', state: 'WA', zip: 98119, neighborhood: `Queen Anne`, cost: `$$`, cuisine: `European Beer Hall`, website: `queenannebeerhall.com`, description: `The Queen Anne Beerhall brings an authentic beer hall experience to Seattle. It is a tradition that Europeans have enjoyed for centuries - communal tables. The spaetzle is top notch and nothing beats that giant, soft pretzel.`},
 {id: 13, name: `The Other Coast Café`, street_address: `721 E Pike St`, city: 'Seattle', state: 'WA', zip: 98122, neighborhood: `Capital Hill`, cost: `$`, cuisine: `Deli`, website: `othercoastcafe.com`, description: `Delightful sandwiches in a pinch and their special is always interesting`},
 {id: 14, name: `The Wandering Goose`, street_address: `403 15th Ave E`, city: 'Seattle', state: 'WA', zip: 98112, neighborhood: `East Capital Hill`, cost: `$$`, cuisine: `Americana`, website: `thewanderinggoose.com/`, description: `Sweet little Wandering Goose is worth squeezing into for a hearty brunch of comfort food with Southern inflections. Meals consist of personal cast-iron skillets full of brisket, grits, seasonal veggies, and the like, or breakfast sandwiches with legit Southern-style biscuits. The Friday night fried-chicken dinners are on point, as are the myriad, enormous pastries and cakes. The cinnamon roll is a must.`},
{id: 15, name: `Ba Bar`, street_address: `550 12th Ave`, city: 'Seattle', state: 'WA', zip: 98122, neighborhood: `Capital Hill`, cost: `$$`, cuisine: `Vietnamese`, website: `babarseattle.com/`, description: `Eric and Sophie Banh have named their Central District restaurant "ba," the Vietnamese word for "father." As such, their menu is a beautiful homage to their Saigon childhoods. Authentic comfort food and street fare bursting with Southeast Asian flavors, from congee to pho and vermicelli bowls, are all notable in their simplicity and depth of flavor. Fresh pastries from early 'til late and Jon Christiansen’s expertly crafted cocktails make this spot — now a mini-chain — a complete package.`},
{id: 16, name: `Matt's in the Market`, street_address: `94 Pike St`, city: 'Seattle', state: 'WA', zip: 98101, neighborhood: `Pike Place Market`, cost: `$$$`, cuisine: `Americana`, website: `mattsinthemarket.com/`, description: `The place hasn't lost any of its popularity since founder Matt Janke sold the restaurant to Dan Bugge in 2006. The seafood is absolutely fresh and the location overlooking Pike Place Market's famous sign is about as Seattle as it gets.`},
{id: 17, name: `Marination Mai Kai`, street_address: `1660 Harbor Ave SW`, city: 'Seattle', state: 'WA', zip: 98127, neighborhood: `Alki`, cost: `$`, cuisine: `Hawaiian`, website: `marinationmobile.com/#about`, description: `This place is all about breakfast burritos in the morning, spam sliders for lunch, and kimchi fried rice and boozy shaved ice at night. The dining room overlooks Seattle and the patios is one of the best in the city.`},
{id: 18, name: `Taqueria La Fondita #2`, street_address: `9811 15th Ave SW`, city: 'Seattle', state: 'WA', zip: 98106, neighborhood: `Georgetown`, cost: `$$`, cuisine: `Mexican`, website: `visitwhitecenter.com/biz/taqueria-la-fondita/`, description: `This inexpensive, stationary food truck is one of the Seattle area's best, and it might make transplants forget how far they are from America's southern border. Plates get piled up with carne asada, adobada, and lengua tacos, and a special request for extra grilled mini-onions and spicy serrano peppers is key. The burritos are epic, too.`},
{id: 19, name: `Xi'an Noodles`, street_address: `5259 University Way NE`, city: 'Seattle', state: 'WA', zip: 98105, neighborhood: `University District`, cost: `$`, cuisine: `Chinese`, website: `too cool for the web`, description: `Some of the best noodles in town. Be prepared to fight for a table after placing your order and don't you dare leave without getting the lamb.`}
]).then(() => {
        return knex.raw(`SELECT setval('restaurants_id_seq', (SELECT MAX(id) FROM restaurants));`)
      })
};
