exports.seed = knex => {
  // Deletes ALL existing entries
  return knex('restaurants').insert([
        {id: 1, name: 'Lost Lake Cafe & Lounge', street_address: '1505 10th Ave', city: 'Seattle', state: 'WA', zip: 98122, image: 'https://static1.squarespace.com/static/58768c62725e253cc7141608/58a386978419c21e08120d20/58c0856e3e00be4c006d71ce/1489012221205/Lost+Lake+Cafe-web+2.jpg?format=1500w', cost: '$', cuisine: 'Americana', website: 'https://www.lostlakecafe.com/', description: `Delicious, laid back lounge modeled after the locally shot Twin Peaks mystery thriller.`},
        {id: 2, name: 'Bar del Corso', street_address: '3057 Beacon Ave S', city: 'Seattle', state: 'WA', zip: 98144, image: 'http://farm7.staticflickr.com/6198/6064330804_d1ba351737.jpg', cost: '$$', cuisine: 'Pizza', website: 'http://www.bardelcorso.com/', description: `Bar del Corso is a pizzeria, restaurant and bar in the Beacon Hill neighborhood of Seattle, featuring wood-fired pizza, and Italian small dishes. We showcase local, seasonal produce, Italian salumi and cheese, and regional Italian wines. Classic Italian cocktails, local craft beer, cider, and spirits are served from our bar. Our bread and desserts are made in-house, with espresso and after dinner drinks available.`},
        {id: 3, name: 'Altstadt', street_address: '209 1st Avenue South', city: 'Seattle', state: 'WA', zip: 98104, image: 'http://www.altstadtseattle.com/wp-content/uploads/2015/04/Altstadt_Seattle10821.jpg', cost: '$$', cuisine: 'German', website: 'http://www.altstadtseattle.com/', description: `Altstadt is a unique experience in Pioneer Square and Seattle in general. We make the unfamiliar (whether it be beer, liquor, or food) familiar and bring the German hospitality traditions to our own community. With a warm, homey atmosphere and product found nowhere else in the area, we know the experience of coming to Altstadt is one of a kind, whether it be a guest’s first, or fiftieth time.`},
        {id: 4, name: 'Che Sara Sara', street_address: '222 1st Avenue South', city: 'Seattle', state: 'WA', zip: 98104, image: 'http://farm7.staticflickr.com/6198/6064330804_d1ba351737.jpg', cost: '$$', cuisine: 'Italian', website: 'http://seattleslittleitaly.com/che-sara-sara/', description: `Che Sara Sara is a 20-seat restaurant almost exclusively serving the food and wine of the Puglia region of Italy.  This is one of the only mono, regional restaurants (of any type) in all of Seattle.  Enjoy traditional dishes from Puglia, such as O recchiette Con Broccoli De Rape and stop by for l’aperitivo!`}
      ]).then(() => {
        return knex.raw(`SELECT setval('restaurants_id_seq', (SELECT MAX(id) FROM restaurants));`)
      })
};
