exports.seed = knex => {
  // Deletes ALL existing entries
  return knex('restaurant_category').insert([
        {id: 1, restaurant_id: 1, category_id: 1},
        {id: 2, restaurant_id: 1, category_id: 2},
        {id: 3, restaurant_id: 1, category_id: 5},
        {id: 4, restaurant_id: 2, category_id: 4},
        {id: 5, restaurant_id: 2, category_id: 3},
        {id: 6, restaurant_id: 3, category_id: 8},
        {id: 7, restaurant_id: 3, category_id: 1},
        {id: 8, restaurant_id: 3, category_id: 2},
        {id: 9, restaurant_id: 3, category_id: 5},
        {id: 10, restaurant_id: 4, category_id: 3},
        {id: 11, restaurant_id: 4, category_id: 3},
        {id: 12, restaurant_id: 5, category_id: 9},
        {id: 13, restaurant_id: 5, category_id: 3},
        {id: 14, restaurant_id: 6, category_id: 5},
        {id: 15, restaurant_id: 6, category_id: 10},
        {id: 16, restaurant_id: 7, category_id: 9},
        {id: 17, restaurant_id: 7, category_id: 2},
        {id: 18, restaurant_id: 7, category_id: 3},
        {id: 19, restaurant_id: 8, category_id: 3},
        {id: 20, restaurant_id: 8, category_id: 4},
        {id: 21, restaurant_id: 9, category_id: 10},
        {id: 22, restaurant_id: 9, category_id: 11},
        {id: 23, restaurant_id: 10, category_id: 2},
        {id: 24, restaurant_id: 10, category_id: 3},
        {id: 25, restaurant_id: 10, category_id: 4},
        {id: 27, restaurant_id: 10, category_id: 11},
        {id: 28, restaurant_id: 11, category_id: 1},
        {id: 29, restaurant_id: 11, category_id: 3},
        {id: 30, restaurant_id: 11, category_id: 4},
        {id: 31, restaurant_id: 11, category_id: 7},
        {id: 32, restaurant_id: 12, category_id: 7},
        {id: 33, restaurant_id: 12, category_id: 10},
        {id: 34, restaurant_id: 13, category_id: 1},
        {id: 35, restaurant_id: 13, category_id: 4},
        {id: 36, restaurant_id: 14, category_id: 9},
        {id: 37, restaurant_id: 14, category_id: 12},
        {id: 38, restaurant_id: 8, category_id: 12},
        {id: 39, restaurant_id: 15, category_id: 2},
        {id: 40, restaurant_id: 15, category_id: 10},
        {id: 41, restaurant_id: 15, category_id: 11},
        {id: 42, restaurant_id: 16, category_id: 13},
        {id: 43, restaurant_id: 16, category_id: 11},
        {id: 44, restaurant_id: 16, category_id: 4},
        {id: 45, restaurant_id: 17, category_id: 1},
        {id: 46, restaurant_id: 17, category_id: 9},
        {id: 47, restaurant_id: 17, category_id: 12},
        {id: 48, restaurant_id: 18, category_id: 1},
        {id: 49, restaurant_id: 18, category_id: 5},
        {id: 50, restaurant_id: 18, category_id: 12},
        {id: 51, restaurant_id: 19, category_id: 3},
        {id: 52, restaurant_id: 19, category_id: 12}
      ]).then(() => {
        return knex.raw(`SELECT setval('restaurant_category_id_seq', (SELECT MAX(id) FROM restaurant_category));`)
      })
};
